clc; clear; close all;

addpath('../..');

obj = PTV.calibration(...
    '.', 21.7, './lagData.mat', 'name', 'stereo_cal1', 'checkFrameNumber', 8, ...
    'disparityBlockSize', 5, 'disparityContrastThreshold', 0.1, ...
    'disparityUniquenessThreshold', 0, 'disparityMax', 16*9);