function [] = createTrackFile(fileName)
%CREATETRACKFILE Creates an empty track file

    fid = fopen(fileName, 'w');
    fileHeader = ['Step\t Global left frame\t Global right frame\t Time\t' ...
        'Left video\t Left frame ID\t Right video\t Right frame ID\t Track ID\t' ...
        'Age\t TotalVisibleCount\t TotalInvisibleCount\t' ...
        'ConsecutiveInvisibleCount\t Estimated\t Lost\t', ...
        'x\t y\t Disparity\t Area\t Major ax\t Minor ax\t', ...
        'Orientation\t Eccentricity\t r2\t Perimeter\t BB Width\t BB Height\t', ...
        'X\t Y\t Z\t Length H\t Length V\n'];
    
    fprintf(fid, fileHeader);
    fclose(fid);
end