function this = progressWindow(this)
    this.GUI.fig = figure('Units', 'normalized',...
                  'Position', [0.7 0.3 0.25 0.31],...
                  'Menubar', 'none',...
                  'Name', 'Tracking progress',...
                  'NumberTitle', 'off',...
                  'resize', 'off');


    this.GUI.rightVideoPanel = uipanel(...
        'Units', 'normalized',...
        'Title', 'Right video',...
        'Tag','leftVideoPanel',...
        'Position', [0.03 0.03 1-0.03*2 0.3],...
        'FontSize', 14);
    labels = {'Open video', 'Current frame', 'Detected particles', 'Left time'};
    tags = {'OpenVideo', 'CurrentFrame', 'TotalParticles', 'LeftTime'};
    y = 0.86;
    for l=1:length(labels)
        uicontrol('style','text',...
            'Parent', this.GUI.rightVideoPanel, 'unit', 'normalized', 'Position', [0.03 y-0.22*l 0.45 0.3], ...
            'String', labels{l}, 'FontSize', 13, 'FontWeight', 'bold', ...
            'HorizontalAlignment', 'left');

        this.GUI.labels.rightVideo.(tags{l}) = uicontrol('Style', 'text',...
            'Parent', this.GUI.rightVideoPanel, 'Unit', 'normalized', 'Position', [0.5 y-0.22*l 0.45 0.3], ...
            'String', '', 'FontSize', 13, 'HorizontalAlignment', 'left');
    end

    %% Left video panel
    this.GUI.leftVideoPanel = uipanel(...
        'Units', 'normalized',...
        'Title', 'Left video',...
        'Tag','leftVideoPanel',...
        'Position', [0.03 0.37 1-0.03*2 0.3],...
        'FontSize', 14);
    y = 0.86;
    for l=1:length(labels)
        uicontrol('style','text',...
            'Parent', this.GUI.leftVideoPanel, 'unit', 'normalized', 'Position', [0.03 y-0.22*l 0.45 0.3], ...
            'String', labels{l}, 'FontSize', 13, 'FontWeight', 'bold', ...
            'HorizontalAlignment', 'left');

        this.GUI.labels.leftVideo.(tags{l}) = uicontrol('Style', 'text',...
            'Parent', this.GUI.leftVideoPanel, 'Unit', 'normalized', 'Position', [0.5 y-0.22*l 0.45 0.3], ...
            'String', '', 'FontSize', 13, 'HorizontalAlignment', 'left');
    end

    %% Overall progress
    this.GUI.globalPanel = uipanel(...
        'Units', 'normalized',...
        'Title', 'Overall progress',...
        'Position', [0.03 0.7 1-0.03*2 0.3],...
        'FontSize', 14);
    labels = {'Step', 'Total tracks', 'Processing time', 'Left time'};
    tags = {'Step', 'TotalTracks', 'MeanTime', 'LeftTime'};

    y = 0.86;
    for l=1:length(labels)
        uicontrol('style','text',...
            'Parent', this.GUI.globalPanel, 'Unit', 'normalized', 'Position', [0.03 y-0.22*l 0.45 0.3], ...
            'String', labels{l}, 'FontSize', 13, 'FontWeight', 'bold', ...
            'HorizontalAlignment', 'left');

        this.GUI.labels.global.(tags{l}) = uicontrol('Style', 'text',...
            'Parent', this.GUI.globalPanel, 'Unit', 'normalized', 'Position', [0.5 y-0.22*l 0.45 0.3], ...
            'String', '', 'FontSize', 13, 'HorizontalAlignment', 'left');
    end                 
end